//! Typed IPC surface shared with the frontend.
//!
//! Every Tauri command is registered once, in `crate::specta_builder`. The
//! same builder feeds the runtime invoke handler and the generated
//! `src/bindings.ts`, so the frontend cannot call a command or use a type that
//! Rust does not define.
//!
//! Regenerate with `pnpm bindings`. `cargo test` fails when the committed file
//! is stale.

use specta_typescript::Typescript;

const BINDINGS_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../src/bindings.ts");

fn export(path: &str) {
    crate::specta_builder()
        .export(
            Typescript::default().header(
                "// Generated by src-tauri/src/bindings.rs. Do not edit; run `pnpm bindings`.\n",
            ),
            path,
        )
        .expect("failed to export TypeScript bindings");
}

#[test]
fn bindings_are_up_to_date() {
    if std::env::var_os("UPDATE_BINDINGS").is_some() {
        export(BINDINGS_PATH);
        return;
    }

    let generated_path =
        std::env::temp_dir().join(format!("conductor-bindings-{}.ts", std::process::id()));
    export(generated_path.to_str().expect("temp path is UTF-8"));
    let generated = std::fs::read_to_string(&generated_path).expect("read generated bindings");
    let _ = std::fs::remove_file(&generated_path);
    let committed = std::fs::read_to_string(BINDINGS_PATH).unwrap_or_default();

    assert!(
        generated == committed,
        "src/bindings.ts is stale; run `pnpm bindings` and commit the result"
    );
}
