// Generated by src-tauri/src/bindings.rs. Do not edit; run `pnpm bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getWorkspaceState: (key: string) => __TAURI_INVOKE<unknown | null>("get_workspace_state", { key }),
	setWorkspaceState: (key: string, value: FrontendJson) => __TAURI_INVOKE<null>("set_workspace_state", { key, value }),
	/**
	 *  The one way editors save variables: every change in one transaction, so a
	 *  failure leaves nothing half-applied (for example a variable moved between
	 *  scopes is never deleted from one and missing from the other).
	 */
	applyVariableChanges: (changes: VariableChange[]) => __TAURI_INVOKE<null>("apply_variable_changes", { changes }),
	createEnvironment: (input: CreateEnvironmentInput) => __TAURI_INVOKE<string>("create_environment", { input }),
	createFolder: (input: CreateFolderInput) => __TAURI_INVOKE<string>("create_folder", { input }),
	createRequest: (input: CreateRequestInput) => __TAURI_INVOKE<CreateRequestResult>("create_request", { input }),
	deleteEnvironment: (environmentId: string) => __TAURI_INVOKE<null>("delete_environment", { environmentId }),
	/**
	 *  Copies an environment and all its variables into the same collection,
	 *  named "<name> copy". Returns the new environment's id.
	 */
	duplicateEnvironment: (input: DuplicateEnvironmentInput) => __TAURI_INVOKE<string>("duplicate_environment", { input }),
	deleteNode: (nodeId: string) => __TAURI_INVOKE<null>("delete_node", { nodeId }),
	duplicateRequest: (input: DuplicateRequestInput) => __TAURI_INVOKE<DuplicateRequestResult>("duplicate_request", { input }),
	getCollectionTree: (collectionId: string) => __TAURI_INVOKE<CollectionNode[]>("get_collection_tree", { collectionId }),
	getRequest: (requestId: string) => __TAURI_INVOKE<RequestDetail>("get_request", { requestId }),
	importPostmanEnvironment: (collectionId: string, postmanJson: string, fileName: string | null) => __TAURI_INVOKE<string>("import_postman_environment", { collectionId, postmanJson, fileName }),
	importPostmanCollection: (postmanJson: string) => __TAURI_INVOKE<string>("import_postman_collection", { postmanJson }),
	listCollections: () => __TAURI_INVOKE<CollectionSummary[]>("list_collections"),
	listEnvironments: () => __TAURI_INVOKE<EnvironmentSummary[]>("list_environments"),
	listVariables: (target: VariableTarget) => __TAURI_INVOKE<VariableEntry[]>("list_variables", { target }),
	renameEnvironment: (input: RenameEnvironmentInput) => __TAURI_INVOKE<null>("rename_environment", { input }),
	resolveRequest: (request: RequestDetail, environmentId: string | null) => __TAURI_INVOKE<ResolvedRequestPreview>("resolve_request", { request, environmentId }),
	moveNode: (input: MoveNodeInput) => __TAURI_INVOKE<null>("move_node", { input }),
	saveRequest: (request: RequestDetail) => __TAURI_INVOKE<null>("save_request", { request }),
	saveTextFile: (input: SaveTextFileInput) => __TAURI_INVOKE<null>("save_text_file", { input }),
	saveResponseBody: (input: SaveResponseBodyInput) => __TAURI_INVOKE<null>("save_response_body", { input }),
	sendRequest: (input: SendRequestInput) => __TAURI_INVOKE<SendRequestResult>("send_request", { input }),
};

/** Events */
export const events = {
	appMenuAction: makeEvent<AppMenuAction>("app-menu-action"),
};

/* Types */
export type ApiKeyLocation = "query" | 
/**  Also what any other stored value reads as, matching how it is sent. */
"header";

/**
 *  What the user picked in the app menu, sent to the webview as the typed
 *  `app-menu-action` event.
 */
export type AppMenuAction = "open-request" | "new-request" | "duplicate-request" | "save-request" | "send-request" | "close-request" | "toggle-sidebar" | "focus-url" | "settings" | "check-for-updates";

export type AuthConfig = {
	authType: AuthType,
	token?: string | null,
	username?: string | null,
	password?: string | null,
	key?: string | null,
	value?: string | null,
	addTo?: ApiKeyLocation | null,
};

/**  The strings are what `auth_json` holds, which Postman import also writes. */
export type AuthType = 
/**  An explicit "send none", unlike no auth at all, which inherits. */
"noauth" | "bearer" | "basic" | "apikey" | 
/**
 *  An imported type we cannot apply (such as `oauth2`); it adds nothing
 *  to the request but still stops inheritance.
 */
"unsupported";

export type BodyField = {
	key: string,
	value: string,
	enabled?: boolean,
	fieldType?: BodyFieldType,
	filePath?: string | null,
	contentType?: string | null,
};

export type BodyFieldType = "file" | 
/**  Also what a missing or unknown stored type reads as. */
"text";

/**
 *  The strings are what `body_json` holds, including rows saved before this
 *  was an enum.
 */
export type BodyMode = "none" | "raw" | "formdata" | "urlencoded" | "graphql" | "file" | 
/**  A Postman mode we cannot send (such as `binary`); it sends no body. */
"unsupported";

export type CollectionNode = {
	id: string,
	parentId: string | null,
	position: number,
	name: string,
} & CollectionNodeKind;

/**
 *  Only a folder has children and only a request has a request behind it, so
 *  neither side needs a null for the other's fields.
 */
export type CollectionNodeKind = { kind: "folder"; children: CollectionNode[] } | { kind: "request"; requestId: string; method: string };

export type CollectionSummary = {
	id: string,
	name: string,
};

export type CreateEnvironmentInput = {
	collectionId: string,
	name: string,
};

export type CreateFolderInput = {
	collectionId: string,
	parentId: string | null,
	position: number,
	name: string,
};

export type CreateRequestInput = {
	collectionId: string,
	parentId: string | null,
	position: number,
	name: string,
};

export type CreateRequestResult = {
	requestId: string,
	nodeId: string,
};

export type DuplicateEnvironmentInput = {
	environmentId: string,
};

export type DuplicateRequestInput = {
	requestId: string,
};

export type DuplicateRequestResult = {
	requestId: string,
	nodeId: string,
};

export type EnvironmentSummary = {
	id: string,
	/**  The collection that owns this environment. */
	collectionId: string,
	name: string,
};

export type FileBody = {
	path?: string | null,
	contentType?: string | null,
};

/**  JSON blob whose shape is owned by the frontend; Rust only stores it. */
export type FrontendJson = unknown;

export type GraphqlBody = {
	query?: string,
	variables?: string,
};

export type KeyValue = {
	key: string,
	value: string,
	enabled?: boolean,
};

export type MoveNodeInput = {
	nodeId: string,
	parentId: string | null,
	position: number,
};

export type RenameEnvironmentInput = {
	environmentId: string,
	name: string,
};

export type RequestBody = {
	mode: BodyMode,
	raw?: string,
	rawLanguage?: string | null,
	formData?: BodyField[],
	urlencoded?: KeyValue[],
	graphql?: GraphqlBody | null,
	file?: FileBody | null,
};

export type RequestDetail = {
	id: string,
	collectionId: string,
	name: string,
	method: string,
	url: string,
	headers: KeyValue[],
	query: KeyValue[],
	pathParams: KeyValue[],
	auth: AuthConfig | null,
	body: RequestBody | null,
	preRequestScript: unknown | null,
	testScript: unknown | null,
};

export type ResolvedRequestPreview = {
	/**
	 *  From the request's folders and collection in the database, so it
	 *  follows moves without reloading the request.
	 */
	inheritedAuth: AuthConfig | null,
	/**  Keys only, in the order they first appear. */
	unresolvedVariables: string[],
	/**
	 *  Every variable the request uses that has a value. `None` for a
	 *  sensitive variable, whose value stays in Rust.
	 */
	variableValues: { [key in string]: string | null },
};

/**  Binary bodies stay as raw bytes in Rust; see `save_response_body`. */
export type ResponseBodyFormat = "json" | "text" | "binary";

export type ResponseHeader = {
	key: string,
	value: string,
};

export type SaveResponseBodyInput = {
	historyId: string,
	path: string,
};

export type SaveTextFileInput = {
	path: string,
	contents: string,
};

export type SendRequestInput = {
	request: RequestDetail,
	environmentId?: string | null,
};

export type SendRequestResult = {
	historyId: string,
	statusCode: number,
	durationMs: number,
	headers: ResponseHeader[],
	/**  Pretty-printed for JSON, as received for text, empty for binary. */
	body: string,
	bodyBytes: number,
	bodyContentType: string | null,
	bodyFormat: ResponseBodyFormat,
	/**  What the save dialog suggests, from `Content-Disposition` when sent. */
	downloadFileName: string,
	updatedVariables: KeyValue[],
	variableWarnings: string[],
};

/**
 *  What one editor changed in one target: keys to set and keys to remove.
 *  Keys it did not touch are not sent, so saving never overwrites a value
 *  changed elsewhere (a script, another window) in the meantime.
 */
export type VariableChange = {
	target: VariableTarget,
	upserts: VariableEntry[],
	deletes: string[],
};

/**
 *  A variable as the editors show it. Which target it belongs to is the
 *  target it was listed from or is saved to.
 */
export type VariableEntry = {
	key: string,
	value: string,
	enabled: boolean,
	sensitive: boolean,
};

/**
 *  Which set of variables a command reads or writes. The ids it holds are the
 *  only way to name a collection or environment, so a scope without its id
 *  cannot be expressed.
 */
export type VariableTarget = { scope: "global" } | { scope: "collection"; collectionId: string } | { scope: "environment"; environmentId: string };

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

