// Generated by src-tauri/src/bindings.rs. Do not edit; run `pnpm bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	databaseStatus: () => __TAURI_INVOKE<DatabaseStatus>("database_status"),
	getWorkspaceState: (key: string) => __TAURI_INVOKE<unknown | null>("get_workspace_state", { key }),
	setWorkspaceState: (key: string, value: FrontendJson) => __TAURI_INVOKE<null>("set_workspace_state", { key, value }),
	createEnvironment: (input: CreateEnvironmentInput) => __TAURI_INVOKE<string>("create_environment", { input }),
	createFolder: (input: CreateFolderInput) => __TAURI_INVOKE<string>("create_folder", { input }),
	createRequest: (input: CreateRequestInput) => __TAURI_INVOKE<CreateRequestResult>("create_request", { input }),
	deleteEnvironment: (environmentId: string) => __TAURI_INVOKE<null>("delete_environment", { environmentId }),
	deleteNode: (nodeId: string) => __TAURI_INVOKE<null>("delete_node", { nodeId }),
	deleteRequest: (requestId: string) => __TAURI_INVOKE<null>("delete_request", { requestId }),
	duplicateRequest: (input: DuplicateRequestInput) => __TAURI_INVOKE<DuplicateRequestResult>("duplicate_request", { input }),
	getCollectionTree: (collectionId: string) => __TAURI_INVOKE<CollectionNode[]>("get_collection_tree", { collectionId }),
	getRequest: (requestId: string) => __TAURI_INVOKE<RequestDetail>("get_request", { requestId }),
	importPostmanEnvironment: (postmanJson: string, fileName: string | null) => __TAURI_INVOKE<string>("import_postman_environment", { postmanJson, fileName }),
	importPostmanCollection: (postmanJson: string) => __TAURI_INVOKE<string>("import_postman_collection", { postmanJson }),
	listCollections: () => __TAURI_INVOKE<CollectionSummary[]>("list_collections"),
	listEnvironments: () => __TAURI_INVOKE<EnvironmentSummary[]>("list_environments"),
	listVariables: (scope: string, collectionId: string | null, environmentId: string | null) => __TAURI_INVOKE<VariableEntry[]>("list_variables", { scope, collectionId, environmentId }),
	renameEnvironment: (input: RenameEnvironmentInput) => __TAURI_INVOKE<null>("rename_environment", { input }),
	resolveRequest: (request: RequestDetail, environmentId: string | null) => __TAURI_INVOKE<ResolvedRequestPreview>("resolve_request", { request, environmentId }),
	moveNode: (input: MoveNodeInput) => __TAURI_INVOKE<null>("move_node", { input }),
	saveRequest: (request: RequestDetail) => __TAURI_INVOKE<null>("save_request", { request }),
	saveTextFile: (input: SaveTextFileInput) => __TAURI_INVOKE<null>("save_text_file", { input }),
	saveVariables: (scope: string, collectionId: string | null, environmentId: string | null, variables: VariableEntry[]) => __TAURI_INVOKE<null>("save_variables", { scope, collectionId, environmentId, variables }),
	sendRequest: (input: SendRequestInput) => __TAURI_INVOKE<SendRequestResult>("send_request", { input }),
};

/* Types */
export type AuthConfig = {
	authType: string,
	token?: string | null,
	username?: string | null,
	password?: string | null,
	key?: string | null,
	value?: string | null,
	addTo?: string | null,
};

export type BodyField = {
	key: string,
	value: string,
	enabled?: boolean,
	fieldType?: string,
	filePath?: string | null,
	contentType?: string | null,
};

export type CollectionNode = {
	id: string,
	collectionId: string,
	parentId: string | null,
	position: number,
	kind: string,
	name: string,
	requestId: string | null,
	method: string | null,
	children: CollectionNode[],
};

export type CollectionSummary = {
	id: string,
	name: string,
	source: string,
	updatedAt: string,
};

export type CreateEnvironmentInput = {
	name: string,
};

export type CreateFolderInput = {
	collectionId: string,
	parentId: string | null,
	position: number,
	name: string,
};

export type CreateRequestInput = {
	collectionId: string,
	parentId: string | null,
	position: number,
	name: string,
};

export type CreateRequestResult = {
	requestId: string,
	nodeId: string,
};

export type DatabaseStatus = {
	path: string,
	schemaVersion: number,
	collectionCount: number,
	requestCount: number,
};

export type DuplicateRequestInput = {
	requestId: string,
};

export type DuplicateRequestResult = {
	requestId: string,
	nodeId: string,
};

export type EnvironmentSummary = {
	id: string,
	name: string,
	updatedAt: string,
};

export type FileBody = {
	path?: string | null,
	contentType?: string | null,
};

/**  JSON blob whose shape is owned by the frontend; Rust only stores it. */
export type FrontendJson = unknown;

export type GraphqlBody = {
	query?: string,
	variables?: string,
};

export type KeyValue = {
	key: string,
	value: string,
	enabled?: boolean,
};

export type MoveNodeInput = {
	nodeId: string,
	parentId: string | null,
	position: number,
};

export type RenameEnvironmentInput = {
	environmentId: string,
	name: string,
};

export type RequestBody = {
	mode: string,
	raw?: string,
	rawLanguage?: string | null,
	formData?: BodyField[],
	urlencoded?: KeyValue[],
	graphql?: GraphqlBody | null,
	file?: FileBody | null,
};

export type RequestDetail = {
	id: string,
	collectionId: string,
	name: string,
	method: string,
	url: string,
	headers: KeyValue[],
	query: KeyValue[],
	pathParams: KeyValue[],
	auth: AuthConfig | null,
	inheritedAuth: AuthConfig | null,
	effectiveAuth: AuthConfig | null,
	body: RequestBody | null,
	preRequestScript: unknown | null,
	testScript: unknown | null,
	updatedAt: string,
};

export type ResolvedRequestPreview = {
	url: string,
	headers: KeyValue[],
	query: KeyValue[],
	body: RequestBody | null,
	unresolvedVariables: UnresolvedVariable[],
};

export type ResponseHeader = {
	key: string,
	value: string,
};

export type SaveTextFileInput = {
	path: string,
	contents: string,
};

export type SendRequestInput = {
	request: RequestDetail,
	environmentId?: string | null,
};

export type SendRequestResult = {
	historyId: string,
	statusCode: number,
	statusText: string,
	durationMs: number,
	headers: ResponseHeader[],
	body: string,
	bodyBytes: number,
	bodyContentType: string | null,
	bodyFormat: string,
	updatedVariables: KeyValue[],
	variableWarnings: string[],
	unresolvedVariables: UnresolvedVariable[],
};

export type UnresolvedVariable = {
	key: string,
	locations: string[],
};

export type VariableEntry = {
	scope: string,
	collectionId: string | null,
	environmentId: string | null,
	key: string,
	value: string,
	initialValue: string | null,
	enabled: boolean,
	sensitive: boolean,
	variableType?: string | null,
};

